import fs from "fs";
import path from "path";
import * as tjs from "typescript-json-schema";

const settings = {
  required: true,
  ref: false,
};
const compilerOptions = {
  strictNullChecks: true,
};

const schemasPath = "src/types/schemas/index.ts";
const program = tjs.getProgramFromFiles(
  [path.resolve(schemasPath)],
  compilerOptions,
  "./"
);

const schema = tjs.generateSchema(program, "*", settings);
fs.writeFileSync(
  "dist/_schema.ts",
  "// THIS FILE IS AUTO-GENERATED BY SCHEMAGENERATOR.JS\n" +
    "export const _schema = " +
    JSON.stringify(schema, null, 4) +
    ";"
);
