// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.areas */
export type AreaId = string & { __brand: 'AreasId' };

/** Represents the table public.areas */
export default interface Area {
  id: AreaId;

  name: string;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.areas */
export interface AreasInitializer {
  /** Default value: gen_random_uuid() */
  id?: AreaId;

  name: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.areas */
export interface AreasMutator {
  id?: AreaId;

  name?: string;

  created_at?: Date;

  updated_at?: Date;
}
