// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.camera_log_event_type */
type CameraLogEventType = 
  | 'camera_online'
  | 'camera_offline'
  | 'error'
  | 'viewer_connected'
  | 'viewer_disconnected';

export default CameraLogEventType;
