// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as CameraStatus } from './CameraStatus';
import type { AreaId } from './Area';

/** Identifier type for public.cameras */
export type CameraId = string & { __brand: 'CamerasId' };

/** Represents the table public.cameras */
export default interface Camera {
  id: CameraId;

  name: string;

  token: string | null;

  local_address: string | null;

  status: CameraStatus | null;

  connected_at: Date | null;

  area_id: AreaId;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.cameras */
export interface CamerasInitializer {
  /** Default value: gen_random_uuid() */
  id?: CameraId;

  name: string;

  token?: string | null;

  local_address?: string | null;

  /** Default value: 'inactive'::camera_status */
  status?: CameraStatus | null;

  connected_at?: Date | null;

  area_id: AreaId;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.cameras */
export interface CamerasMutator {
  id?: CameraId;

  name?: string;

  token?: string | null;

  local_address?: string | null;

  status?: CameraStatus | null;

  connected_at?: Date | null;

  area_id?: AreaId;

  created_at?: Date;

  updated_at?: Date;
}
