// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as CameraLogEventType } from './CameraLogEventType';
import type { CameraId } from './Camera';

/** Identifier type for public.camera_logs */
export type CameraLogId = string & { __brand: 'CameraLogsId' };

/** Represents the table public.camera_logs */
export default interface CameraLog {
  id: CameraLogId;

  event_type: CameraLogEventType;

  event_at: Date;

  event_details: any | null;

  camera_id: CameraId;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.camera_logs */
export interface CameraLogsInitializer {
  /** Default value: gen_random_uuid() */
  id?: CameraLogId;

  event_type: CameraLogEventType;

  event_at: Date;

  /** Default value: '{}'::jsonb */
  event_details?: any | null;

  camera_id: CameraId;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.camera_logs */
export interface CameraLogsMutator {
  id?: CameraLogId;

  event_type?: CameraLogEventType;

  event_at?: Date;

  event_details?: any | null;

  camera_id?: CameraId;

  created_at?: Date;

  updated_at?: Date;
}
