// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.camera_status */
type CameraStatus = 
  | 'active'
  | 'inactive'
  | 'maintenance';

export default CameraStatus;
