// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { AreaId } from './Area';
import type { default as UserAreaRole } from './UserAreaRole';

/** Identifier type for public.user_areas */
export type UserAreaId = string & { __brand: 'UserAreasId' };

/** Represents the table public.user_areas */
export default interface UserArea {
  id: UserAreaId;

  user_id: UserId;

  area_id: AreaId;

  created_at: Date;

  updated_at: Date;

  role: UserAreaRole | null;
}

/** Represents the initializer for the table public.user_areas */
export interface UserAreasInitializer {
  /** Default value: gen_random_uuid() */
  id?: UserAreaId;

  user_id: UserId;

  area_id: AreaId;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;

  /** Default value: 'user'::user_area_role */
  role?: UserAreaRole | null;
}

/** Represents the mutator for the table public.user_areas */
export interface UserAreasMutator {
  id?: UserAreaId;

  user_id?: UserId;

  area_id?: AreaId;

  created_at?: Date;

  updated_at?: Date;

  role?: UserAreaRole | null;
}
