// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.user_area_role */
type UserAreaRole = 
  | 'owner'
  | 'user';

export default UserAreaRole;
