// THIS FILE IS AUTO-GENERATED BY swagger/generate.ts
export const _schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "AreaId": {
            "description": "Identifier type for public.areas",
            "allOf": [
                {
                    "type": "object",
                    "properties": {
                        "__brand": {
                            "type": "string",
                            "const": "AreasId"
                        }
                    },
                    "required": [
                        "__brand"
                    ]
                },
                {
                    "type": "string"
                }
            ]
        },
        "Area": {
            "description": "Represents the table public.areas",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Identifier type for public.areas",
                    "allOf": [
                        {
                            "type": "object",
                            "properties": {
                                "__brand": {
                                    "type": "string",
                                    "const": "AreasId"
                                }
                            },
                            "required": [
                                "__brand"
                            ]
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "required": [
                "created_at",
                "id",
                "name",
                "updated_at"
            ]
        },
        "AreasInitializer": {
            "description": "Represents the initializer for the table public.areas",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Default value: gen_random_uuid()",
                    "allOf": [
                        {
                            "type": "object",
                            "properties": {
                                "__brand": {
                                    "type": "string",
                                    "const": "AreasId"
                                }
                            },
                            "required": [
                                "__brand"
                            ]
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "created_at": {
                    "description": "Default value: CURRENT_TIMESTAMP",
                    "type": "string",
                    "format": "date-time"
                },
                "updated_at": {
                    "description": "Default value: CURRENT_TIMESTAMP",
                    "type": "string",
                    "format": "date-time"
                }
            },
            "required": [
                "name"
            ]
        },
        "AreasMutator": {
            "description": "Represents the mutator for the table public.areas",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Identifier type for public.areas",
                    "allOf": [
                        {
                            "type": "object",
                            "properties": {
                                "__brand": {
                                    "type": "string",
                                    "const": "AreasId"
                                }
                            },
                            "required": [
                                "__brand"
                            ]
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "SuccessResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "const": true
                },
                "data": {
                    "type": "object"
                }
            },
            "required": [
                "data",
                "success"
            ]
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "const": false
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "errors": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "required": [
                        "errors"
                    ]
                }
            },
            "required": [
                "data",
                "success"
            ]
        },
        "CreateAreaRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ]
        },
        "AreaResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "const": true
                },
                "data": {
                    "description": "Represents the table public.areas",
                    "type": "object",
                    "properties": {
                        "id": {
                            "description": "Identifier type for public.areas",
                            "allOf": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "__brand": {
                                            "type": "string",
                                            "const": "AreasId"
                                        }
                                    },
                                    "required": [
                                        "__brand"
                                    ]
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "name": {
                            "type": "string"
                        },
                        "created_at": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "updated_at": {
                            "type": "string",
                            "format": "date-time"
                        }
                    },
                    "required": [
                        "created_at",
                        "id",
                        "name",
                        "updated_at"
                    ]
                }
            },
            "required": [
                "data",
                "success"
            ]
        },
        "AreasResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "const": true
                },
                "data": {
                    "type": "array",
                    "items": {
                        "description": "Represents the table public.areas",
                        "type": "object",
                        "properties": {
                            "id": {
                                "description": "Identifier type for public.areas",
                                "allOf": [
                                    {
                                        "type": "object",
                                        "properties": {
                                            "__brand": {
                                                "type": "string",
                                                "const": "AreasId"
                                            }
                                        },
                                        "required": [
                                            "__brand"
                                        ]
                                    },
                                    {
                                        "type": "string"
                                    }
                                ]
                            },
                            "name": {
                                "type": "string"
                            },
                            "created_at": {
                                "type": "string",
                                "format": "date-time"
                            },
                            "updated_at": {
                                "type": "string",
                                "format": "date-time"
                            }
                        },
                        "required": [
                            "created_at",
                            "id",
                            "name",
                            "updated_at"
                        ]
                    }
                }
            },
            "required": [
                "data",
                "success"
            ]
        },
        "CameraStatus": {
            "description": "Represents the enum public.camera_status",
            "enum": [
                "active",
                "inactive",
                "maintenance"
            ],
            "type": "string"
        },
        "CameraId": {
            "description": "Identifier type for public.cameras",
            "allOf": [
                {
                    "type": "object",
                    "properties": {
                        "__brand": {
                            "type": "string",
                            "const": "CamerasId"
                        }
                    },
                    "required": [
                        "__brand"
                    ]
                },
                {
                    "type": "string"
                }
            ]
        },
        "Camera": {
            "description": "Represents the table public.cameras",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Identifier type for public.cameras",
                    "allOf": [
                        {
                            "type": "object",
                            "properties": {
                                "__brand": {
                                    "type": "string",
                                    "const": "CamerasId"
                                }
                            },
                            "required": [
                                "__brand"
                            ]
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "local_address": {
                    "type": "string"
                },
                "status": {
                    "description": "Represents the enum public.camera_status",
                    "enum": [
                        "active",
                        "inactive",
                        "maintenance"
                    ],
                    "type": "string"
                },
                "connected_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "area_id": {
                    "description": "Identifier type for public.areas",
                    "allOf": [
                        {
                            "type": "object",
                            "properties": {
                                "__brand": {
                                    "type": "string",
                                    "const": "AreasId"
                                }
                            },
                            "required": [
                                "__brand"
                            ]
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "required": [
                "area_id",
                "connected_at",
                "created_at",
                "id",
                "local_address",
                "name",
                "status",
                "token",
                "updated_at"
            ]
        },
        "CamerasInitializer": {
            "description": "Represents the initializer for the table public.cameras",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Default value: gen_random_uuid()",
                    "allOf": [
                        {
                            "type": "object",
                            "properties": {
                                "__brand": {
                                    "type": "string",
                                    "const": "CamerasId"
                                }
                            },
                            "required": [
                                "__brand"
                            ]
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "local_address": {
                    "type": "string"
                },
                "status": {
                    "description": "Default value: 'inactive'::camera_status",
                    "enum": [
                        "active",
                        "inactive",
                        "maintenance"
                    ],
                    "type": "string"
                },
                "connected_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "area_id": {
                    "description": "Identifier type for public.areas",
                    "allOf": [
                        {
                            "type": "object",
                            "properties": {
                                "__brand": {
                                    "type": "string",
                                    "const": "AreasId"
                                }
                            },
                            "required": [
                                "__brand"
                            ]
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "created_at": {
                    "description": "Default value: CURRENT_TIMESTAMP",
                    "type": "string",
                    "format": "date-time"
                },
                "updated_at": {
                    "description": "Default value: CURRENT_TIMESTAMP",
                    "type": "string",
                    "format": "date-time"
                }
            },
            "required": [
                "area_id",
                "name"
            ]
        },
        "CamerasMutator": {
            "description": "Represents the mutator for the table public.cameras",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Identifier type for public.cameras",
                    "allOf": [
                        {
                            "type": "object",
                            "properties": {
                                "__brand": {
                                    "type": "string",
                                    "const": "CamerasId"
                                }
                            },
                            "required": [
                                "__brand"
                            ]
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "local_address": {
                    "type": "string"
                },
                "status": {
                    "description": "Represents the enum public.camera_status",
                    "enum": [
                        "active",
                        "inactive",
                        "maintenance"
                    ],
                    "type": "string"
                },
                "connected_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "area_id": {
                    "description": "Identifier type for public.areas",
                    "allOf": [
                        {
                            "type": "object",
                            "properties": {
                                "__brand": {
                                    "type": "string",
                                    "const": "AreasId"
                                }
                            },
                            "required": [
                                "__brand"
                            ]
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "CreateCameraRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "local_address": {
                    "type": "string"
                },
                "area_id": {
                    "description": "Identifier type for public.areas",
                    "allOf": [
                        {
                            "type": "object",
                            "properties": {
                                "__brand": {
                                    "type": "string",
                                    "const": "AreasId"
                                }
                            },
                            "required": [
                                "__brand"
                            ]
                        },
                        {
                            "type": "string"
                        }
                    ]
                }
            },
            "required": [
                "area_id",
                "local_address",
                "name"
            ]
        },
        "CameraResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "const": true
                },
                "data": {
                    "description": "Represents the table public.cameras",
                    "type": "object",
                    "properties": {
                        "id": {
                            "description": "Identifier type for public.cameras",
                            "allOf": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "__brand": {
                                            "type": "string",
                                            "const": "CamerasId"
                                        }
                                    },
                                    "required": [
                                        "__brand"
                                    ]
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "name": {
                            "type": "string"
                        },
                        "token": {
                            "type": "string"
                        },
                        "local_address": {
                            "type": "string"
                        },
                        "status": {
                            "description": "Represents the enum public.camera_status",
                            "enum": [
                                "active",
                                "inactive",
                                "maintenance"
                            ],
                            "type": "string"
                        },
                        "connected_at": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "area_id": {
                            "description": "Identifier type for public.areas",
                            "allOf": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "__brand": {
                                            "type": "string",
                                            "const": "AreasId"
                                        }
                                    },
                                    "required": [
                                        "__brand"
                                    ]
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "created_at": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "updated_at": {
                            "type": "string",
                            "format": "date-time"
                        }
                    },
                    "required": [
                        "area_id",
                        "connected_at",
                        "created_at",
                        "id",
                        "local_address",
                        "name",
                        "status",
                        "token",
                        "updated_at"
                    ]
                }
            },
            "required": [
                "data",
                "success"
            ]
        },
        "CamerasResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "const": true
                },
                "data": {
                    "type": "array",
                    "items": {
                        "description": "Represents the table public.cameras",
                        "type": "object",
                        "properties": {
                            "id": {
                                "description": "Identifier type for public.cameras",
                                "allOf": [
                                    {
                                        "type": "object",
                                        "properties": {
                                            "__brand": {
                                                "type": "string",
                                                "const": "CamerasId"
                                            }
                                        },
                                        "required": [
                                            "__brand"
                                        ]
                                    },
                                    {
                                        "type": "string"
                                    }
                                ]
                            },
                            "name": {
                                "type": "string"
                            },
                            "token": {
                                "type": "string"
                            },
                            "local_address": {
                                "type": "string"
                            },
                            "status": {
                                "description": "Represents the enum public.camera_status",
                                "enum": [
                                    "active",
                                    "inactive",
                                    "maintenance"
                                ],
                                "type": "string"
                            },
                            "connected_at": {
                                "type": "string",
                                "format": "date-time"
                            },
                            "area_id": {
                                "description": "Identifier type for public.areas",
                                "allOf": [
                                    {
                                        "type": "object",
                                        "properties": {
                                            "__brand": {
                                                "type": "string",
                                                "const": "AreasId"
                                            }
                                        },
                                        "required": [
                                            "__brand"
                                        ]
                                    },
                                    {
                                        "type": "string"
                                    }
                                ]
                            },
                            "created_at": {
                                "type": "string",
                                "format": "date-time"
                            },
                            "updated_at": {
                                "type": "string",
                                "format": "date-time"
                            }
                        },
                        "required": [
                            "area_id",
                            "connected_at",
                            "created_at",
                            "id",
                            "local_address",
                            "name",
                            "status",
                            "token",
                            "updated_at"
                        ]
                    }
                }
            },
            "required": [
                "data",
                "success"
            ]
        },
        "UserId": {
            "description": "Identifier type for public.users",
            "allOf": [
                {
                    "type": "object",
                    "properties": {
                        "__brand": {
                            "type": "string",
                            "const": "UsersId"
                        }
                    },
                    "required": [
                        "__brand"
                    ]
                },
                {
                    "type": "string"
                }
            ]
        },
        "User": {
            "description": "Represents the table public.users",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Identifier type for public.users",
                    "allOf": [
                        {
                            "type": "object",
                            "properties": {
                                "__brand": {
                                    "type": "string",
                                    "const": "UsersId"
                                }
                            },
                            "required": [
                                "__brand"
                            ]
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "required": [
                "created_at",
                "id",
                "name",
                "password",
                "updated_at",
                "username"
            ]
        },
        "UsersInitializer": {
            "description": "Represents the initializer for the table public.users",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Default value: gen_random_uuid()",
                    "allOf": [
                        {
                            "type": "object",
                            "properties": {
                                "__brand": {
                                    "type": "string",
                                    "const": "UsersId"
                                }
                            },
                            "required": [
                                "__brand"
                            ]
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "created_at": {
                    "description": "Default value: CURRENT_TIMESTAMP",
                    "type": "string",
                    "format": "date-time"
                },
                "updated_at": {
                    "description": "Default value: CURRENT_TIMESTAMP",
                    "type": "string",
                    "format": "date-time"
                }
            },
            "required": [
                "name",
                "password",
                "username"
            ]
        },
        "UsersMutator": {
            "description": "Represents the mutator for the table public.users",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Identifier type for public.users",
                    "allOf": [
                        {
                            "type": "object",
                            "properties": {
                                "__brand": {
                                    "type": "string",
                                    "const": "UsersId"
                                }
                            },
                            "required": [
                                "__brand"
                            ]
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "UserResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "const": true
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "description": "Identifier type for public.users",
                            "allOf": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "__brand": {
                                            "type": "string",
                                            "const": "UsersId"
                                        }
                                    },
                                    "required": [
                                        "__brand"
                                    ]
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "name": {
                            "type": "string"
                        },
                        "created_at": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "updated_at": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "username": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "created_at",
                        "id",
                        "name",
                        "updated_at",
                        "username"
                    ]
                }
            },
            "required": [
                "data",
                "success"
            ]
        },
        "UserLoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            },
            "required": [
                "password",
                "username"
            ]
        },
        "UserLoginResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "const": true
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "token": {
                            "type": "string"
                        },
                        "user": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "description": "Identifier type for public.users",
                                    "allOf": [
                                        {
                                            "type": "object",
                                            "properties": {
                                                "__brand": {
                                                    "type": "string",
                                                    "const": "UsersId"
                                                }
                                            },
                                            "required": [
                                                "__brand"
                                            ]
                                        },
                                        {
                                            "type": "string"
                                        }
                                    ]
                                },
                                "name": {
                                    "type": "string"
                                },
                                "created_at": {
                                    "type": "string",
                                    "format": "date-time"
                                },
                                "updated_at": {
                                    "type": "string",
                                    "format": "date-time"
                                },
                                "username": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "created_at",
                                "id",
                                "name",
                                "updated_at",
                                "username"
                            ]
                        }
                    },
                    "required": [
                        "token",
                        "user"
                    ]
                }
            },
            "required": [
                "data",
                "success"
            ]
        },
        "UserJWTPayload": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "string"
                }
            },
            "required": [
                "userId"
            ]
        }
    }
};