name: Railway Deploy

on:
  push:
    branches: [main]

jobs:
  api-deploy:
    name: Deploy API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install packages
        run: npm install --workspace api

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service ${{ vars.API_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  frontend-deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install packages
        run: npm install --workspace web

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service ${{ vars.FRONTEND_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
